site_name: OSCAR Documentation
site_description: "Documentation of the OSCAR Project, corpus, tools and community."
site_author: "OSCAR Team"
docs_dir: docs/
repo_name: "oscar-corpus"
repo_url: "https://github.com/oscar-corpus/documentation"
# nav:
#     - Home: index.md
theme:
  name: "material"
  features:
    - content.code.annotate
markdown_extensions:
  - meta
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: plotly
          class: mkdocs-plotly
          format: !!python/name:mkdocs_plotly_plugin.fences.fence_plotly
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - tables

extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.filesize.js
  - javascripts/tablesort.js

plugins:
  - plotly
