site_name: OSCAR Documentation
site_description: 'Documentation of the OSCAR Project, corpus, tools and community.'
site_author: 'OSCAR Team'
docs_dir: docs/
repo_name: 'oscar-corpus'
repo_url: 'https://github.com/oscar-corpus/documentation'
nav:
    - Home: index.md
theme:
  name: 'material'
