site_name: OSCAR Documentation
site_description: 'Documentation of the OSCAR Project, corpus, tools and community.'
site_author: 'OSCAR Team'
docs_dir: docs/
repo_name: 'oscar-corpus'
repo_url: 'https://github.com/oscar-corpus/documentation'
# nav:
#     - Home: index.md
theme:
  name: 'material'
  features:
    - content.code.annotate 
markdown_extensions:
  - meta
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - tables

